@echo off
REM Auto-generated by generate_model_deployment_matrix.py
set PHOENIX_CURRENT_ROLE=x5
set PHOENIX_GATEWAY_ROLE=host
set PHOENIX_TARGET_ARCH=aarch64
set PHOENIX_CONNECTION=websocket
set PHOENIX_DISABLE_EDGE_IMAGE=0
set PHOENIX_DISABLE_EDGE_SPEECH=0
