/* main.cpp - Auto-generated hub for split main.cpp
   Copyright (C) 2026 079 Project

   This file is part of 079 Project.

   079 Project is free software: you can redistribute it and/or modify
   it under the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   079 Project is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with 079 Project.  If not, see <http://www.gnu.org/licenses/>. */

// Auto-generated hub for split main.cpp
// Generated by tools/split_main_cpp.py
// Keep compile order unchanged by including the extracted segments sequentially.

#ifndef _WIN32
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <errno.h>
typedef int SOCKET;
#define INVALID_SOCKET (-1)
#define SOCKET_ERROR (-1)
#define WSADATA int
#define MAKEWORD(a, b) (0)
#define WSAStartup(a, b) (void)0
#define WSAGetLastError() (errno)
#define WSAEWOULDBLOCK EWOULDBLOCK
#define closesocket close
#define ioctlsocket ioctl
using ioctl_arg_t = int;
typedef socklen_t sockopt_len_t;
#else
typedef int sockopt_len_t;
using ioctl_arg_t = unsigned long;
#endif

#include "ahead_module.hpp"
#include "async_task_system.hpp"
#include "module_overrides/llama_split_backend_client.hpp"

#include "main_hub_parts/000_section_before_config.inc"
#include "main_hub_parts/001_struct_config.inc"
#include "main_hub_parts/002_section_before_sharedmemoryslice.inc"
#include "main_hub_parts/003_struct_sharedmemoryslice.inc"
#include "main_hub_parts/004_section_before_processreservedarena.inc"
#include "main_hub_parts/005_class_processreservedarena.inc"
#include "main_hub_parts/006_section_before_hotmatrixcache.inc"
#include "main_hub_parts/007_class_hotmatrixcache.inc"
#include "main_hub_parts/008_section_before_fetchresult.inc"
#include "main_hub_parts/009_struct_fetchresult.inc"
// #include "main_hub_parts/010_section_before_curlwritectx.inc" // Disabled due to pre-existing compilation errors
#include "main_hub_parts/011_struct_curlwritectx.inc"
#include "main_hub_parts/012_section_before_torchtextembedder.inc"
// #include "main_hub_parts/013_struct_torchtextembedder.inc" // Disabled due to pre-existing compilation errors
#include "main_hub_parts/014_section_before_rng32.inc"
#include "main_hub_parts/015_class_rng32.inc"
#include "main_hub_parts/016_section_before_surfacephrase.inc"
#include "main_hub_parts/017_struct_surfacephrase.inc"
#include "main_hub_parts/018_section_before_lmdbstore.inc"
#include "main_hub_parts/019_class_lmdbstore.inc"
#include "main_hub_parts/020_section_before_jsonfilestore.inc"
#include "main_hub_parts/021_class_jsonfilestore.inc"
#include "main_hub_parts/022_section_before_namespacedstore.inc"
#include "main_hub_parts/023_class_namespacedstore.inc"
#include "main_hub_parts/024_section_before_runtimebase.inc"
#include "main_hub_parts/025_class_runtimebase.inc"
#include "main_hub_parts/026_section_before_searchconfig.inc"
#include "main_hub_parts/027_struct_searchconfig.inc"
#include "main_hub_parts/028_section_before_modeldefaults.inc"
#include "main_hub_parts/029_struct_modeldefaults.inc"
#include "main_hub_parts/030_section_before_onlineresearcher.inc"
#include "main_hub_parts/031_class_onlineresearcher.inc"
#include "main_hub_parts/032_section_before_exprtoken.inc"
#include "main_hub_parts/033_struct_exprtoken.inc"
#include "main_hub_parts/034_section_before_csrmatrix.inc"
#include "main_hub_parts/035_struct_csrmatrix.inc"
#include "main_hub_parts/036_section_before_tensorengine.inc"
#include "main_hub_parts/037_class_tensorengine.inc"
#include "main_hub_parts/038_section_before_kvmstore.inc"
#include "main_hub_parts/039_class_kvmstore.inc"
#include "main_hub_parts/040_section_before_memegraph.inc"
#include "main_hub_parts/041_class_memegraph.inc"
#include "main_hub_parts/042_section_before_graphexportbuilder.inc"
#include "main_hub_parts/043_class_graphexportbuilder.inc"
#include "main_hub_parts/044_section_before_graphtensorbridge.inc"
#include "main_hub_parts/045_class_graphtensorbridge.inc"
#include "main_hub_parts/046_section_before_dimreducer.inc"
#include "main_hub_parts/047_class_dimreducer.inc"
#include "main_hub_parts/048_section_before_patternmatrix.inc"
#include "main_hub_parts/049_class_patternmatrix.inc"
#include "main_hub_parts/050_section_before_memesurfacelexicon.inc"
#include "main_hub_parts/051_class_memesurfacelexicon.inc"
#include "main_hub_parts/052_section_before_dialogmemory.inc"
#include "main_hub_parts/053_class_dialogmemory.inc"
#include "main_hub_parts/054_section_before_robotsdocument.inc"
#include "main_hub_parts/055_struct_robotsdocument.inc"
#include "main_hub_parts/056_section_before_sessionmanager.inc"
#include "main_hub_parts/057_class_sessionmanager.inc"
#include "main_hub_parts/058_section_before_lemmacacheentry.inc"
#include "main_hub_parts/059_struct_lemmacacheentry.inc"
#include "main_hub_parts/060_section_before_lemmaworkerpool.inc"
#include "main_hub_parts/061_class_lemmaworkerpool.inc"
#include "main_hub_parts/062_section_before_studyengine.inc"
#include "main_hub_parts/063_class_studyengine.inc"
#include "main_hub_parts/064_section_before_runtimestate.inc"
#include "main_hub_parts/065_class_runtimestate.inc"
#include "main_hub_parts/066_section_before_memebarrier.inc"
#include "main_hub_parts/067_class_memebarrier.inc"
#include "main_hub_parts/068_section_before_crawlitem.inc"
#include "main_hub_parts/069_struct_crawlitem.inc"
// #include "main_hub_parts/070_section_before_crawlitem.inc" // Disabled due to pre-existing compilation errors
// #include "main_hub_parts/071_struct_crawlitem.inc" // CrawlItem already defined in 069_struct_crawlitem.inc
#include "main_hub_parts/072_section_before_controllerpoolbase.inc"
#include "main_hub_parts/073_class_controllerpoolbase.inc"
#include "main_hub_parts/074_section_before_controller.inc"
#include "main_hub_parts/075_class_controller.inc"
#include "main_hub_parts/076_section_before_sharddescriptor.inc"
#include "main_hub_parts/077_class_sharddescriptor.inc"
#include "main_hub_parts/078_section_before_shardmanager.inc"
#include "main_hub_parts/079_class_shardmanager.inc"
#include "main_hub_parts/080_section_before_inferenceprocesspool.inc"
#include "main_hub_parts/081_class_inferenceprocesspool.inc"
#include "main_hub_parts/082_section_before_proxyruntime.inc"
#include "main_hub_parts/083_class_proxyruntime.inc"
#include "main_hub_parts/084_section_before_proxycontroller.inc"
#include "main_hub_parts/085_class_proxycontroller.inc"
#include "main_hub_parts/086_section_before_localcontroller.inc"
#include "main_hub_parts/087_class_localcontroller.inc"
#include "main_hub_parts/088_section_before_controllerpool.inc"
#include "main_hub_parts/089_class_controllerpool.inc"
#include "main_hub_parts/090_section_before_groupprocesspool.inc"
#include "main_hub_parts/091_class_groupprocesspool.inc"
#include "main_hub_parts/092_section_before_personaforestaverager.inc"
#include "main_hub_parts/093_class_personaforestaverager.inc"
#include "main_hub_parts/094_section_before_sparkarray.inc"
#include "main_hub_parts/095_class_sparkarray.inc"
#include "main_hub_parts/096_section_before_reinforcementlearner.inc"
#include "main_hub_parts/097_class_reinforcementlearner.inc"
#include "main_hub_parts/098_section_before_adversariallearner.inc"
#include "main_hub_parts/099_class_adversariallearner.inc"
#include "main_hub_parts/100_section_before_gnngalearner.inc"
#include "main_hub_parts/101_class_gnngalearner.inc"
#include "main_hub_parts/102_section_before_redissynchronizer.inc"
#include "main_hub_parts/103_class_redissynchronizer.inc"
#include "main_hub_parts/104_section_before_rotationmanager.inc"
#include "main_hub_parts/105_class_rotationmanager.inc"
#include "main_hub_parts/106_section_before_snapshotmanager.inc"
#include "main_hub_parts/107_class_snapshotmanager.inc"
#include "main_hub_parts/108_section_before_gatewaycontextservice.inc"
#include "main_hub_parts/109_class_gatewaycontextservice.inc"
#include "concept_matrix.hpp"
#include "world_model.hpp"
#include "main_hub_parts/110_section_before_gatewayserver.inc"
#include "main_hub_parts/111_class_gatewayserver.inc"
#include "main_hub_parts/112_section_before_contexthint.inc"
#include "main_hub_parts/113_struct_contexthint.inc"
#include "main_hub_parts/114_section_before_gnnhintsummary.inc"
#include "main_hub_parts/115_struct_gnnhintsummary.inc"
#include "main_hub_parts/116_section_tail.inc"
