#!/usr/bin/env python3
"""
generate_model_deployment_matrix.py - v7.0 649-endpoint model deployment generator.

The full matrix is:

    3 (current) * 3 (gateway) * 3 (target arch) * 3 (connection) *
    2 (llm placement)  * 2 (vision placement) * 2 (speech placement)
    + 1 (all-auto default)
    = 81 * 8 + 1 = 649

This matches the documented dimensions: current machine, external gateway,
target architecture, connection type, and per-modality placement (llm/vision/speech).

Commands:
    # single non-interactive output
    python tools/generate_model_deployment_matrix.py --non-interactive \
        --current-role host --gateway-role x5 --target-arch x86_64 \
        --connection http-json --llm-placement remote \
        --vision-placement local --speech-placement remote

    # dump all 649 configs
    python tools/generate_model_deployment_matrix.py --dump-all

    # validate all configs are JSON-parseable and count them
    python tools/generate_model_deployment_matrix.py --enumerate
"""

import argparse
import json
import os
import sys
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The 7 option lists.  3*3*3*3*2*2*2 = 648  + 1 default = 649.
CURRENTS = ["host", "edge", "x5"]
GATEWAYS = ["host", "edge", "x5"]
ARCHS = ["x86_64", "aarch64", "hybrid"]
CONNECTIONS = ["http-json", "grpc", "websocket"]
LLM_PLACEMENTS = ["local", "remote"]
VISION_PLACEMENTS = ["local", "remote"]
SPEECH_PLACEMENTS = ["local", "remote"]


def default_port(conn: str, is_llm: bool) -> int:
    if is_llm:
        if conn == "http-json":
            return 11434
        if conn == "grpc":
            return 11434
        if conn == "websocket":
            return 11434
    if conn == "http-json":
        return 5000
    if conn == "grpc":
        return 50051
    if conn == "websocket":
        return 8080
    return 5000


def default_path(conn: str, is_llm: bool) -> str:
    if is_llm:
        return ""
    if conn == "http-json":
        return "/infer"
    if conn == "grpc":
        return "/Infer"
    if conn == "websocket":
        return "/ws"
    return "/infer"


def default_method(conn: str, is_llm: bool) -> str:
    if is_llm and conn == "http-json":
        return "ollama"
    return conn


def base_ip(role: str) -> str:
    if role == "x5":
        return "http://192.168.0.107"
    if role == "edge":
        return "http://192.168.0.11"
    return "http://127.0.0.1"


def default_local_backend(arch: str, placement: str) -> str:
    if placement != "local":
        return "auto"
    if arch == "aarch64":
        return "bpu"
    if arch == "hybrid":
        return "gpu"
    return "cpu"


def build_record(placement: str, role: str, conn: str, is_llm: bool,
                 arch: str, llm_model: str = "", timeout: int = 30000) -> dict:
    if placement == "local":
        return {"placement": placement, "localBackend": default_local_backend(arch, placement)}

    port = default_port(conn, is_llm)
    path = default_path(conn, is_llm)
    url = f"{base_ip(role)}:{port}{path}"

    model_name = ""
    if is_llm:
        model_name = llm_model

    return {
        "placement": placement,
        "remote": {
            "url": url,
            "method": default_method(conn, is_llm),
            "modelName": model_name,
            "authToken": "",
            "timeoutMs": timeout,
            "headers": {},
        },
    }


def compile_env_bat(current: str, gateway: str, arch: str, conn: str) -> str:
    """Return a Windows batch file text for conditional compile flags."""
    # BPU support is meaningful when at least one edge target (x5/aarch64)
    # is involved.  host-only x86 builds can optionally disable it.
    disable_image = "0"
    disable_speech = "0"
    if current == "host" and gateway == "host" and arch == "x86_64":
        # pure x86 host build may not have the BPU headers
        disable_image = "0"  # keep; runtime fallback handles it

    lines = [
        "@echo off",
        "REM Auto-generated by generate_model_deployment_matrix.py",
        f"set PHOENIX_CURRENT_ROLE={current}",
        f"set PHOENIX_GATEWAY_ROLE={gateway}",
        f"set PHOENIX_TARGET_ARCH={arch}",
        f"set PHOENIX_CONNECTION={conn}",
        f"set PHOENIX_DISABLE_EDGE_IMAGE={disable_image}",
        f"set PHOENIX_DISABLE_EDGE_SPEECH={disable_speech}",
    ]
    return "\r\n".join(lines) + "\r\n"


def build_matrix_entry(current: str, gateway: str, arch: str, conn: str,
                       llm: str, vision: str, speech: str,
                       llm_model: str) -> dict:
    return {
        "llm": build_record(llm, current, conn, True, arch, llm_model, 120000),
        "vision": build_record(vision, current, conn, False, arch, timeout=30000),
        "speech": build_record(speech, current, conn, False, arch, timeout=30000),
        "_metadata": {
            "current": current,
            "gateway": gateway,
            "arch": arch,
            "connection": conn,
        },
    }


def default_all_auto() -> dict:
    """The 649th default config: all auto, same host, http-json."""
    return {
        "llm": build_record("auto", "host", "http-json", True, "x86_64",
                            llm_model="llama3.1:8b", timeout=120000),
        "vision": build_record("auto", "host", "http-json", False, "x86_64", timeout=30000),
        "speech": build_record("auto", "host", "http-json", False, "x86_64", timeout=30000),
        "_metadata": {
            "current": "host",
            "gateway": "host",
            "arch": "x86_64",
            "connection": "http-json",
            "note": "default all-auto deployment",
        },
    }


def enumerate_all_configs(llm_model: str = "llama3.1:8b"):
    """Yield every entry of the 649-endpoint matrix (last one is the default)."""
    dims = (
        CURRENTS, GATEWAYS, ARCHS, CONNECTIONS,
        LLM_PLACEMENTS, VISION_PLACEMENTS, SPEECH_PLACEMENTS,
    )
    for combo in product(*dims):
        current, gateway, arch, conn, llm, vision, speech = combo
        cfg = build_matrix_entry(current, gateway, arch, conn, llm, vision,
                                 speech, llm_model)
        cfg.pop("_metadata", None)  # keep output clean for runtime
        yield cfg

    yield default_all_auto()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Phoenix v7.0 649-endpoint model deployment matrix")
    parser.add_argument("--non-interactive", action="store_true",
                        help="Do not prompt; use CLI defaults")
    parser.add_argument("--current-role", default="host", choices=CURRENTS,
                        help="Role of the current machine")
    parser.add_argument("--gateway-role", default="host", choices=GATEWAYS,
                        help="Role of the external/gateway machine")
    parser.add_argument("--target-arch", default="x86_64", choices=ARCHS,
                        help="Target architecture")
    parser.add_argument("--llm-placement", default="local", choices=LLM_PLACEMENTS)
    parser.add_argument("--vision-placement", default="local", choices=VISION_PLACEMENTS)
    parser.add_argument("--speech-placement", default="local", choices=SPEECH_PLACEMENTS)
    parser.add_argument("--connection", default="http-json", choices=CONNECTIONS,
                        help="Default connection/protocol for remote endpoints")
    parser.add_argument("--llm-model", default="llama3.1:8b",
                        help="Remote LLM model name")
    parser.add_argument("-o", "--output", default="config/model_deployment.json",
                        help="Output model deployment JSON")
    parser.add_argument("--env-output",
                        default="compile_env_model_deployment.bat",
                        help="Output compile environment batch file")
    parser.add_argument("--enumerate", action="store_true",
                        help="Enumerate and count all 649 generated configs")
    parser.add_argument("--dump-all", action="store_true",
                        help="Write all 649 configs to config/deployment_matrix/")
    args = parser.parse_args()

    if args.enumerate:
        count = 0
        for _ in enumerate_all_configs(args.llm_model):
            count += 1
        print(f"Matrix size: {count}")
        print(f"  {len(CURRENTS)} currents * {len(GATEWAYS)} gateways * "
              f"{len(ARCHS)} archs * {len(CONNECTIONS)} connections * "
              f"{len(LLM_PLACEMENTS)}^3 placements + 1 default = {count}")
        return 0

    if args.dump_all:
        out_dir = ROOT / "config" / "deployment_matrix"
        out_dir.mkdir(parents=True, exist_ok=True)
        count = 0
        for cfg in enumerate_all_configs(args.llm_model):
            count += 1
            path = out_dir / f"model_deployment_{count:04d}.json"
            with path.open("w", encoding="utf-8") as f:
                json.dump(cfg, f, indent=2, ensure_ascii=False)
        print(f"Wrote {count} configs to {out_dir}")
        return 0

    cfg = build_matrix_entry(
        args.current_role, args.gateway_role, args.target_arch, args.connection,
        args.llm_placement, args.vision_placement, args.speech_placement,
        args.llm_model,
    )
    cfg.pop("_metadata", None)

    out_path = ROOT / args.output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)

    env_path = ROOT / args.env_output
    env_path.parent.mkdir(parents=True, exist_ok=True)
    with env_path.open("w", encoding="utf-8", newline="\r\n") as f:
        f.write(compile_env_bat(args.current_role, args.gateway_role,
                                args.target_arch, args.connection))

    print(f"Wrote {out_path}")
    print(f"Wrote {env_path}")
    print(json.dumps(cfg, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
