from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

DECL_RE = re.compile(r"^\s*(class|struct)\s+([A-Za-z_][A-Za-z0-9_]*)\b")
INCLUDE_RE = re.compile(r'^\s*#include\s+"([^"]+)"\s*$')

HUB_HEADER_LINES = (
    "// Auto-generated hub for split main.cpp",
    "// Generated by tools/split_main_cpp.py",
    "// Keep compile order unchanged by including the extracted segments sequentially.",
)


@dataclass
class LexState:
    in_block_comment: bool = False
    in_line_comment: bool = False
    in_string: bool = False
    string_quote: str = ""
    in_raw_string: bool = False
    raw_end: str = ""


@dataclass
class BlockInfo:
    kind: str
    name: str
    start_line: int
    end_line: int


@dataclass
class ChunkInfo:
    file_name: str
    label: str
    start_line: int
    end_line: int
    line_count: int
    kind: str
    content: str


@dataclass
class HubToken:
    kind: str
    text: str = ""
    file_path: Optional[Path] = None


def sanitize_name(name: str) -> str:
    s = []
    last_us = False
    for ch in name:
        if ch.isalnum():
            s.append(ch.lower())
            last_us = False
        else:
            if not last_us:
                s.append("_")
                last_us = True
    out = "".join(s).strip("_")
    return out or "chunk"


def count_lines(text: str) -> int:
    if not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def rewrite_local_includes(content: str, chunk_dir: Path, source_root: Path) -> str:
    include_re = re.compile(r'^(\s*#include\s+")([^"]+)("\s*)$')
    rel_prefix = os.path.relpath(source_root, chunk_dir).replace("\\", "/")
    if rel_prefix == ".":
        rel_prefix = ""

    rewritten: list[str] = []
    for line in content.splitlines(keepends=True):
        match = include_re.match(line.rstrip("\r\n"))
        if not match:
            rewritten.append(line)
            continue
        include_target = match.group(2)
        if include_target.startswith("."):
            rewritten.append(line)
            continue
        candidate = (source_root / include_target).resolve()
        if not candidate.exists():
            rewritten.append(line)
            continue
        new_target = include_target if not rel_prefix else f"{rel_prefix}/{include_target}"
        newline = "\n" if line.endswith("\n") else ""
        rewritten.append(f'{match.group(1)}{new_target}{match.group(3)}{newline}')
    return "".join(rewritten)


def is_generated_hub(content: str) -> bool:
    return HUB_HEADER_LINES[0] in content and HUB_HEADER_LINES[1] in content


def is_generated_chunk_text(content: str) -> bool:
    lines = content.splitlines()
    if len(lines) < 3:
        return False
    return (
        lines[0].startswith("// Auto-generated from ")
        and lines[1].startswith("// Segment: ")
        and lines[2].startswith("// Original lines: ")
    )


def is_hub_header_line(line: str) -> bool:
    return line.strip() in HUB_HEADER_LINES


def strip_chunk_header(content: str) -> str:
    lines = content.splitlines(keepends=True)
    if len(lines) < 3:
        return content
    if not lines[0].startswith("// Auto-generated from "):
        return content
    if not lines[1].startswith("// Segment: "):
        return content
    if not lines[2].startswith("// Original lines: "):
        return content
    body_start = 3
    if len(lines) > 3 and lines[3].strip() == "":
        body_start = 4
    return "".join(lines[body_start:])


def resolve_include_path(base_dir: Path, include_target: str) -> Path:
    return (base_dir / include_target).resolve()


def is_managed_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    body = strip_chunk_header(text)
    return is_generated_chunk_text(text) or is_generated_hub(body) or is_generated_hub(text)


def expand_generated_text(text: str, base_dir: Path, stack: set[Path]) -> str:
    pieces: list[str] = []
    for line in text.splitlines(keepends=True):
        if is_hub_header_line(line):
            continue
        match = INCLUDE_RE.match(line.rstrip("\r\n"))
        if not match:
            pieces.append(line)
            continue
        candidate = resolve_include_path(base_dir, match.group(1))
        if not is_managed_generated_file(candidate):
            pieces.append(line)
            continue
        pieces.append(expand_generated_file(candidate, stack))
    return "".join(pieces)


def expand_generated_file(path: Path, stack: Optional[set[Path]] = None) -> str:
    resolved = path.resolve()
    if stack is None:
        stack = set()
    if resolved in stack:
        raise SystemExit(f"detected recursive generated include cycle: {resolved}")
    stack.add(resolved)
    try:
        text = resolved.read_text(encoding="utf-8")
        body = strip_chunk_header(text)
        return expand_generated_text(body, resolved.parent, stack)
    finally:
        stack.remove(resolved)


def render_chunk_text(
    source_name: str,
    label: str,
    start_line: int,
    end_line: int,
    content: str,
    chunk_path: Path,
    source_root: Path,
) -> str:
    header = (
        f"// Auto-generated from {source_name}\n"
        f"// Segment: {label}\n"
        f"// Original lines: {start_line}-{end_line}\n\n"
    )
    adjusted = rewrite_local_includes(content, chunk_path.parent, source_root)
    return header + adjusted


def process_char(ch: str, nxt: str, state: LexState):
    if state.in_line_comment:
        return
    if state.in_block_comment:
        if ch == "*" and nxt == "/":
            state.in_block_comment = False
        return
    if state.in_raw_string:
        return
    if state.in_string:
        if ch == "\\":
            return "skip_next"
        if ch == state.string_quote:
            state.in_string = False
            state.string_quote = ""
        return
    if ch == "/" and nxt == "/":
        state.in_line_comment = True
        return
    if ch == "/" and nxt == "*":
        state.in_block_comment = True
        return
    if ch in ('\"', "'"):
        state.in_string = True
        state.string_quote = ch
        return


def find_raw_string_start(text: str, idx: int) -> Optional[tuple[str, int]]:
    if text[idx] != "R" or idx + 1 >= len(text) or text[idx + 1] != '"':
        return None
    j = idx + 2
    delim = []
    while j < len(text) and text[j] != "(":
        delim.append(text[j])
        j += 1
    if j >= len(text):
        return None
    end_marker = ")" + "".join(delim) + '"'
    return end_marker, j


def scan_for_decl(lines: list[str], start_idx: int) -> Optional[BlockInfo]:
    line = lines[start_idx]
    match = DECL_RE.match(line)
    if not match:
        return None
    kind = match.group(1)
    name = match.group(2)

    state = LexState()
    brace_depth = 0
    seen_open = False
    line_idx = start_idx
    col = 0
    while line_idx < len(lines):
        text = lines[line_idx]
        state.in_line_comment = False
        i = col
        while i < len(text):
            if not state.in_block_comment and not state.in_string and not state.in_raw_string:
                raw = find_raw_string_start(text, i)
                if raw is not None:
                    state.in_raw_string = True
                    state.raw_end = raw[0]
                    i = raw[1] + 1
                    continue
            if state.in_raw_string:
                pos = text.find(state.raw_end, i)
                if pos == -1:
                    i = len(text)
                    continue
                state.in_raw_string = False
                state.raw_end = ""
                i = pos + 1
                continue

            ch = text[i]
            nxt = text[i + 1] if i + 1 < len(text) else ""

            result = process_char(ch, nxt, state)
            if result == "skip_next":
                i += 2
                continue
            if state.in_line_comment:
                break
            if state.in_block_comment:
                i += 1
                continue
            if state.in_string:
                i += 1
                continue

            if ch == "{":
                brace_depth += 1
                seen_open = True
            elif ch == "}":
                brace_depth -= 1
            elif ch == ";" and not seen_open:
                return None
            elif ch == ";" and seen_open and brace_depth == 0:
                return BlockInfo(kind=kind, name=name, start_line=start_idx + 1, end_line=line_idx + 1)
            i += 1

        line_idx += 1
        col = 0
    return None


def find_top_level_blocks(lines: list[str]) -> list[BlockInfo]:
    blocks: list[BlockInfo] = []
    next_free_line = 1
    for idx, text in enumerate(lines):
        line_no = idx + 1
        if line_no < next_free_line:
            continue
        if not DECL_RE.match(text):
            continue
        info = scan_for_decl(lines, idx)
        if info is None:
            continue
        blocks.append(info)
        next_free_line = info.end_line + 1
    return blocks


def write_chunk(path: Path, rendered: str):
    path.write_text(rendered, encoding="utf-8", newline="\n")


def build_chunks_from_lines(lines: list[str]) -> list[ChunkInfo]:
    blocks = find_top_level_blocks(lines)
    chunks: list[ChunkInfo] = []

    seq = 0
    cursor = 1

    def emit(kind: str, label: str, start_line: int, end_line: int):
        nonlocal seq
        if end_line < start_line:
            return
        segment_lines = lines[start_line - 1 : end_line]
        content = "".join(segment_lines)
        safe = sanitize_name(label)
        file_name = f"{seq:03d}_{safe}.inc"
        chunks.append(
            ChunkInfo(
                file_name=file_name,
                label=label,
                start_line=start_line,
                end_line=end_line,
                line_count=count_lines(content),
                kind=kind,
                content=content,
            )
        )
        seq += 1

    for block in blocks:
        if cursor < block.start_line:
            emit("section", f"section_before_{block.name}", cursor, block.start_line - 1)
        emit(block.kind, f"{block.kind}_{block.name}", block.start_line, block.end_line)
        cursor = block.end_line + 1
    if cursor <= len(lines):
        emit("section", "section_tail", cursor, len(lines))

    return chunks


def build_chunks_from_text(source_text: str) -> list[ChunkInfo]:
    return build_chunks_from_lines(source_text.splitlines(keepends=True))


def reindex_chunks(chunks: list[ChunkInfo], start_index: int) -> list[ChunkInfo]:
    reindexed: list[ChunkInfo] = []
    next_index = start_index
    for chunk in chunks:
        reindexed.append(
            ChunkInfo(
                file_name=f"{next_index:03d}_{sanitize_name(chunk.label)}.inc",
                label=chunk.label,
                start_line=chunk.start_line,
                end_line=chunk.end_line,
                line_count=chunk.line_count,
                kind=chunk.kind,
                content=chunk.content,
            )
        )
        next_index += 1
    return reindexed


def render_hub_text(output_dir: Path, chunks: list[ChunkInfo]) -> str:
    lines = [
        f"{HUB_HEADER_LINES[0]}\n",
        f"{HUB_HEADER_LINES[1]}\n",
        f"{HUB_HEADER_LINES[2]}\n\n",
    ]
    for chunk in chunks:
        lines.append(f'#include "{output_dir.name}/{chunk.file_name}"\n')
    return "".join(lines)


def parse_manifest_chunk_map(manifest_path: Path) -> dict[str, dict]:
    if not manifest_path.exists():
        return {}
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    chunk_entries = payload.get("chunks", [])
    return {entry.get("file", ""): entry for entry in chunk_entries if entry.get("file")}


def parse_manifest_chunks(manifest_path: Path) -> set[str]:
    return set(parse_manifest_chunk_map(manifest_path))


def parse_chunk_header(text: str) -> tuple[str, int, int, str]:
    lines = text.splitlines()
    label = "chunk"
    start_line = 0
    end_line = 0
    if len(lines) >= 2 and lines[1].startswith("// Segment: "):
        label = lines[1][len("// Segment: ") :].strip() or "chunk"
    if len(lines) >= 3 and lines[2].startswith("// Original lines: "):
        raw_range = lines[2][len("// Original lines: ") :].strip()
        if "-" in raw_range:
            left, right = raw_range.split("-", 1)
            if left.isdigit() and right.isdigit():
                start_line = int(left)
                end_line = int(right)
    kind = label.split("_", 1)[0] if "_" in label else "section"
    return label, start_line, end_line, kind


def load_chunk_info_from_manifest_or_file(file_path: Path, manifest_entry: Optional[dict]) -> ChunkInfo:
    text = file_path.read_text(encoding="utf-8")
    body = strip_chunk_header(text)
    fallback_label, fallback_start, fallback_end, fallback_kind = parse_chunk_header(text)
    label = manifest_entry.get("label", fallback_label) if manifest_entry else fallback_label
    start_line = manifest_entry.get("startLine", fallback_start) if manifest_entry else fallback_start
    end_line = manifest_entry.get("endLine", fallback_end) if manifest_entry else fallback_end
    line_count = manifest_entry.get("lineCount", count_lines(body)) if manifest_entry else count_lines(body)
    kind = manifest_entry.get("kind", fallback_kind) if manifest_entry else fallback_kind
    return ChunkInfo(
        file_name=file_path.name,
        label=label,
        start_line=start_line,
        end_line=end_line,
        line_count=line_count,
        kind=kind,
        content=body,
    )


def resolve_chunk_include(source_path: Path, include_target: str, output_dir: Path) -> Optional[Path]:
    candidate = (source_path.parent / include_target).resolve()
    try:
        candidate.relative_to(output_dir.resolve())
    except ValueError:
        return None
    return candidate


def is_top_level_managed_chunk(source_path: Path, include_target: str, output_dir: Path) -> Optional[Path]:
    candidate = resolve_include_path(source_path.parent, include_target)
    if candidate.parent != output_dir.resolve():
        return None
    if not is_managed_generated_file(candidate):
        return None
    return candidate


def parse_hub_tokens(source_path: Path, output_dir: Path) -> list[HubToken]:
    tokens: list[HubToken] = []
    raw_lines: list[str] = []

    def flush_raw():
        if raw_lines:
            tokens.append(HubToken(kind="raw", text="".join(raw_lines)))
            raw_lines.clear()

    for line in source_path.read_text(encoding="utf-8").splitlines(keepends=True):
        if is_hub_header_line(line):
            continue
        match = INCLUDE_RE.match(line.rstrip("\r\n"))
        if match:
            managed = is_top_level_managed_chunk(source_path, match.group(1), output_dir)
            if managed is not None:
                flush_raw()
                tokens.append(HubToken(kind="include", file_path=managed, text=managed.name))
                continue
        raw_lines.append(line)
    flush_raw()
    return tokens


def reconstruct_source_from_tokens(tokens: list[HubToken]) -> str:
    pieces: list[str] = []
    for token in tokens:
        if token.kind == "include":
            assert token.file_path is not None
            pieces.append(expand_generated_file(token.file_path))
        else:
            pieces.append(token.text)
    return "".join(pieces)


def next_chunk_index_from_tokens(tokens: list[HubToken]) -> int:
    next_index = 0
    for token in tokens:
        if token.kind != "include" or token.file_path is None:
            continue
        prefix = token.file_path.name.split("_", 1)[0]
        if prefix.isdigit():
            next_index = max(next_index, int(prefix) + 1)
    return next_index


def reconstruct_source_from_hub(source_path: Path, output_dir: Path) -> str:
    _ = output_dir
    return expand_generated_text(source_path.read_text(encoding="utf-8"), source_path.parent, set())


def sync_chunks(
    source_name: str,
    source_root: Path,
    output_dir: Path,
    chunks: list[ChunkInfo],
    previous_chunk_files: set[str],
) -> dict[str, int]:
    output_dir.mkdir(parents=True, exist_ok=True)
    new_files = {chunk.file_name for chunk in chunks}
    stats = {"created": 0, "updated": 0, "unchanged": 0, "deleted": 0}

    for chunk in chunks:
        chunk_path = output_dir / chunk.file_name
        rendered = render_chunk_text(
            source_name,
            chunk.label,
            chunk.start_line,
            chunk.end_line,
            chunk.content,
            chunk_path,
            source_root,
        )
        if chunk_path.exists():
            current = chunk_path.read_text(encoding="utf-8")
            if current == rendered:
                stats["unchanged"] += 1
                continue
            stats["updated"] += 1
        else:
            stats["created"] += 1
        write_chunk(chunk_path, rendered)

    for stale_name in sorted(previous_chunk_files - new_files):
        stale_path = output_dir / stale_name
        if stale_path.exists():
            stale_path.unlink()
            stats["deleted"] += 1

    return stats


def delete_chunk_files(output_dir: Path, stale_names: set[str]) -> int:
    deleted = 0
    for stale_name in sorted(stale_names):
        stale_path = output_dir / stale_name
        if stale_path.exists():
            stale_path.unlink()
            deleted += 1
    return deleted


def rewrite_main_cpp(source_path: Path, output_dir: Path, chunks: list[ChunkInfo]):
    source_path.write_text(render_hub_text(output_dir, chunks), encoding="utf-8", newline="\n")


def write_manifest(
    manifest_path: Path,
    source_path: Path,
    chunks: list[ChunkInfo],
    original_line_count: int,
    source_was_hub: bool,
):
    payload = {
        "source": str(source_path.name),
        "sourceWasHub": source_was_hub,
        "originalLineCount": original_line_count,
        "hubLineCount": sum(1 for _ in source_path.read_text(encoding="utf-8").splitlines()),
        "totalChunkLines": sum(chunk.line_count for chunk in chunks),
        "chunkCount": len(chunks),
        "chunks": [
            {
                "file": chunk.file_name,
                "kind": chunk.kind,
                "label": chunk.label,
                "startLine": chunk.start_line,
                "endLine": chunk.end_line,
                "lineCount": chunk.line_count,
            }
            for chunk in chunks
        ],
    }
    manifest_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")


def cleanup_split_artifacts(output_dir: Path, manifest_path: Path):
    if output_dir.exists():
        for path in sorted(output_dir.rglob("*"), reverse=True):
            if path.is_file() and (path.name == "split_manifest.json" or is_managed_generated_file(path)):
                path.unlink()
            elif path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    if manifest_path.exists():
        manifest_path.unlink()
    if output_dir.exists() and not any(output_dir.iterdir()):
        output_dir.rmdir()


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Split a large C++ main.cpp into sequential include fragments, "
            "re-split an edited hub incrementally, or restore the original file."
        )
    )
    parser.add_argument("source", nargs="?", default="main.cpp")
    parser.add_argument("--output-dir", default="main_hub_parts")
    parser.add_argument("--manifest", default="main_hub_parts/split_manifest.json")
    parser.add_argument("--mode", choices=["split", "resplit", "restore"], default="split")
    parser.add_argument("--restore-output")
    parser.add_argument("--cleanup", action="store_true")
    args = parser.parse_args()

    source_path = Path(args.source).resolve()
    if not source_path.exists():
        raise SystemExit(f"source file not found: {source_path}")

    output_dir = (source_path.parent / args.output_dir).resolve()
    manifest_path = (source_path.parent / args.manifest).resolve()

    current_text = source_path.read_text(encoding="utf-8")
    source_was_hub = is_generated_hub(current_text)

    if args.mode == "restore":
        if not source_was_hub:
            raise SystemExit("restore mode requires main.cpp to be an auto-generated hub file.")
        restored_text = reconstruct_source_from_hub(source_path, output_dir)
        restore_target = Path(args.restore_output).resolve() if args.restore_output else source_path
        restore_target.write_text(restored_text, encoding="utf-8", newline="\n")
        if args.cleanup:
            cleanup_split_artifacts(output_dir, manifest_path)
        print(
            json.dumps(
                {
                    "ok": True,
                    "mode": "restore",
                    "source": str(source_path),
                    "restoreTarget": str(restore_target),
                    "restoredLineCount": len(restored_text.splitlines()),
                    "cleanup": args.cleanup,
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return

    if args.mode == "resplit" and not source_was_hub:
        raise SystemExit("resplit mode requires main.cpp to already be an auto-generated hub file.")

    previous_chunk_map = parse_manifest_chunk_map(manifest_path)
    previous_chunk_files = set(previous_chunk_map)

    if source_was_hub:
        tokens = parse_hub_tokens(source_path, output_dir)
        original_text = reconstruct_source_from_tokens(tokens)
        original_line_count = len(original_text.splitlines())

        next_index = next_chunk_index_from_tokens(tokens)
        final_chunks: list[ChunkInfo] = []
        new_chunks: list[ChunkInfo] = []

        for token in tokens:
            if token.kind == "include":
                assert token.file_path is not None
                final_chunks.append(
                    load_chunk_info_from_manifest_or_file(token.file_path, previous_chunk_map.get(token.file_path.name))
                )
                continue
            if not token.text.strip():
                continue
            generated = reindex_chunks(build_chunks_from_text(token.text), next_index)
            next_index += len(generated)
            final_chunks.extend(generated)
            new_chunks.extend(generated)

        sync_stats = sync_chunks(source_path.name, source_path.parent, output_dir, new_chunks, set())
        final_chunk_files = {chunk.file_name for chunk in final_chunks}
        deleted_top_level = delete_chunk_files(output_dir, previous_chunk_files - final_chunk_files)
        sync_stats["deleted"] += deleted_top_level
        rewrite_main_cpp(source_path, output_dir, final_chunks)
        write_manifest(manifest_path, source_path, final_chunks, original_line_count, True)
        chunks = final_chunks
    else:
        source_text = current_text
        original_line_count = len(source_text.splitlines())
        chunks = build_chunks_from_text(source_text)
        sync_stats = sync_chunks(source_path.name, source_path.parent, output_dir, chunks, previous_chunk_files)
        rewrite_main_cpp(source_path, output_dir, chunks)
        write_manifest(manifest_path, source_path, chunks, original_line_count, False)

    hub_line_count = len(source_path.read_text(encoding="utf-8").splitlines())
    total_chunk_lines = sum(chunk.line_count for chunk in chunks)
    total_after = hub_line_count + total_chunk_lines
    print(
        json.dumps(
            {
                "ok": True,
                "mode": "resplit" if source_was_hub or args.mode == "resplit" else "split",
                "source": str(source_path),
                "sourceWasHub": source_was_hub,
                "outputDir": str(output_dir),
                "chunkCount": len(chunks),
                "originalLineCount": original_line_count,
                "hubLineCount": hub_line_count,
                "totalChunkLines": total_chunk_lines,
                "totalLineCountAfter": total_after,
                "createdChunks": sync_stats["created"],
                "updatedChunks": sync_stats["updated"],
                "unchangedChunks": sync_stats["unchanged"],
                "deletedChunks": sync_stats["deleted"],
                "manifest": str(manifest_path),
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
